library("SingleCellExperiment")
library("Seurat")
library("dplyr")
library("Matrix")
library("ggplot2")
library("SingleR")

####################################################
# get the AAV metadata

add_aav_meta <- function(pbmc.merged, aav){
  counts_mtx <- pbmc.merged@assays$RNA@counts
  count_df <- t(as.data.frame(counts_mtx))
  head(count_df[,aav])
  
  asyn_df <- as.data.frame(count_df[,aav])
  head(asyn_df)
  colnames(asyn_df) <- aav
  
  pbmc.merged <- AddMetaData(pbmc.merged, asyn_meta2)
  unique(pbmc.merged@meta.data$AAV.ASYN)
  head(pbmc.all.da@meta.data)
  Idents(object = pbmc.merged) <- pbmc.merged@meta.data$AAV.ASYN
  return(pbmc.merged)
}
####################################################


##############################
# Generate ref for SingleR analysis downstream. Files for this were generated by 1_linnarson_ref_proceccing.py.
#Ref own
p <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref/anndata_from_loom"
# p <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref/out"

mat <- read.csv(paste(p,"COUNT_MATRIX_ADATA_1000.csv", sep="/"), row.names=NULL)
# mat <- read.csv(paste(p,"ad_unfilt_matrix.csv", sep="/"), row.names=NULL)

cells <- read.csv(paste(p,"CELLS_ADATA_1000.csv", sep="/"), row.names=NULL)
# cells <- read.csv(paste(p,"/ad_unfilt_cells.csv", sep="/"), row.names=NULL)

genes <- read.csv(paste(p,"GENES_ADATA_1000.csv", sep="/"), row.names=NULL)
# genes <- read.csv(paste(p,"ad_unfilt_genes.csv", sep="/"), row.names=NULL)

cellids <- read.csv(paste(p, "CELL_IDs_ADATA_1000.csv", sep="/"), row.names=NULL)

head(genes)
cells2 <- unlist(cells[2])
cellids2 <- unlist(cellids[2])
genes2 <- unlist(genes[2])
head(genes2)
length(genes2)
length(cellids2)
length(cells2)
cells2 <- head(cells2, -6)
cellids2 <- head(cellids2, -6)

names(cells2) <- gsub("[[:digit:]]", "", names(cells2))
names(cells2) <- gsub("[[:digit:]]", "", names(cellids2))
names(genes2) <- gsub("[[:digit:]]", "", names(genes2))
dim(mat)
mat <-mat[-27999,-11011]

mat <- t(mat)
########################################
mat <- as(as.matrix(mat), "sparseMatrix")
libsizes <- colSums(mat)
size.factors <- libsizes/mean(libsizes)
logcounts <- log2(t(t(mat)/size.factors) + 1)
logcounts[1:3,1:3]

# the ref data as SE object
se <- SummarizedExperiment(list(logcounts=logcounts))
rownames(se) <- genes2
colnames(se) <- cellids2
se$label.main <- cells2
table(se$label.main)
library('HDF5Array')

outp <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/ref_own_subset_1000range.hdf5"

saveHDF5SummarizedExperiment(se, dir=outp)

################################################
p <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/Parse_samples_TB/rat_complete_onlyrat/all-well/h5ad/all_samples_decomposed_reference/"

library(SingleCellExperiment)

import_h5ad <- function(p) {
  mat.file.parse <- grep("cnt", list.files(p), value=TRUE)
  cell.attr.file <- grep("mta", list.files(p), value=TRUE)
  
  mat.parse <- read.delim(paste0(p, mat.file.parse), header=TRUE, row.names=1, check.names=FALSE, sep = ',')
  cell.attr.parse <- read.delim(paste0(p, cell.attr.file), header=TRUE, row.names=1, check.names=FALSE, sep = ',')
  
  # colnames(mat.parse)
  aav_meta <- mat.parse[c("AAV_ASYN", "AAV_BFP")]
  head(aav_meta)
  
  sce.parse <- SingleCellExperiment(assays = list(counts = t(mat.parse)), colData=cell.attr.parse)
  libsizes <- colSums(mat.parse)
  size.factors <- libsizes/mean(libsizes)
  logcounts <-  log2(t(t(mat.parse)/size.factors) + 1)
  logcounts(sce.parse) <- t(logcounts)
  seurat.parse <- as.Seurat(sce.parse)
  seurat.parse <- AddMetaData(seurat.parse, aav_meta)
  return(seurat.parse)
}

####################
seurat.parse <- import_h5ad(p)



#####################
# Subset the animals from the merged Parse object
cells.use <- colnames(seurat.parse)[which(seurat.parse[[]]['sample'] == "619_GFP")]
pbmc_gfp_bfp <- subset(seurat.parse, cells = cells.use)
table(pbmc_gfp_bfp$sample)

cells.use <- colnames(seurat.parse)[which(seurat.parse[[]]['sample'] == "637_noGFP")]
pbmc_nogfp1 <- subset(seurat.parse, cells = cells.use)
table(pbmc_nogfp1$sample)

cells.use <- colnames(seurat.parse)[which(seurat.parse[[]]['sample'] == "648_noGFP")]
pbmc_nogfp2 <- subset(seurat.parse, cells = cells.use)
table(pbmc_nogfp2$sample)

cells.use <- colnames(seurat.parse)[which(seurat.parse[[]]['sample'] == "650_GFP")]
pbmc_gfp_asyn <- subset(seurat.parse, cells = cells.use)
table(pbmc_gfp_asyn$sample)

###############################################################


# Preprocess
pbmc_gfp_bfp$log10GenesPerUMI <- log10(pbmc_gfp_bfp$nFeature_originalexp) / log10(pbmc_gfp_bfp$nCount_originalexp)
pbmc_gfp_asyn$log10GenesPerUMI <- log10(pbmc_gfp_asyn$nFeature_originalexp) / log10(pbmc_gfp_asyn$nCount_originalexp)
pbmc_nogfp1$log10GenesPerUMI <- log10(pbmc_nogfp1$nFeature_originalexp) / log10(pbmc_nogfp1$nCount_originalexp)
pbmc_nogfp2$log10GenesPerUMI <- log10(pbmc_nogfp2$nFeature_originalexp) / log10(pbmc_nogfp2$nCount_originalexp)

feats <- c("nFeature_originalexp", "nCount_originalexp")
p1 <- VlnPlot(pbmc_gfp_bfp, group.by = "orig.ident", features = feats, pt.size = 0.1, ncol = 3)


pbmc_gfp_asyn@meta.data$orig.ident <- rep("GFP+ Asyn", length(pbmc_gfp_asyn@meta.data$orig.ident))

VlnPlot(pbmc_gfp_asyn, group.by = "orig.ident", features = feats, pt.size = 0.1, ncol = 3) +
  NoLegend()

pbmc_nogfp1@meta.data$orig.ident <- rep("GFP- 1", length(pbmc_nogfp1@meta.data$orig.ident))

VlnPlot(pbmc_nogfp1, group.by = "orig.ident", features = feats, pt.size = 0.1, ncol = 3) +
  NoLegend()

pbmc_nogfp2@meta.data$orig.ident <- rep("GFP- 2", length(pbmc_nogfp2@meta.data$orig.ident))

VlnPlot(pbmc_nogfp2, group.by = "orig.ident", features = feats, pt.size = 0.1, ncol = 3) +
  NoLegend()

pbmc_gfp_bfp@meta.data$orig.ident <- rep("GFP+ tagBFP", length(pbmc_gfp_bfp@meta.data$orig.ident))

VlnPlot(pbmc_gfp_bfp, group.by = "orig.ident", features = feats, pt.size = 0.1, ncol = 3) +
  NoLegend()

library(ggplot2)
par(mfrow=c(2,2))
p1 <- FeatureScatter(pbmc_gfp_bfp, "nCount_originalexp", "nFeature_originalexp", group.by = "orig.ident", pt.size = 0.5) + ggtitle("GFP+ tagBFP")
p2 <- FeatureScatter(pbmc_gfp_asyn, "nCount_originalexp", "nFeature_originalexp", group.by = "orig.ident", pt.size = 0.5)  + ggtitle("GFP+ a-syn")
p3 <- FeatureScatter(pbmc_nogfp1, "nCount_originalexp", "nFeature_originalexp", group.by = "orig.ident", pt.size = 0.5) + ggtitle("GFP- 1")
p4 <- FeatureScatter(pbmc_nogfp2, "nCount_originalexp", "nFeature_originalexp", group.by = "orig.ident", pt.size = 0.5) + ggtitle("GFP- 2")
p1 | p2 | p3 | p4




par(mfrow=c(2,2))
counts_all <- as.data.frame(pbmc_gfp_bfp$nCount_originalexp)
library (plyr)
df_c <- ldply (counts_all, data.frame)
df1 <- df_c[1:length(rownames(df_c)),2]
#df1
p1 <- hist(df1, main="", 
     , xlab = "Number of UMIs per cell GFP+ tagBFP",col = "gray",border = "black", breaks=100)
#######################################
counts_all <- as.data.frame(pbmc_gfp_asyn$nCount_originalexp)
#library (plyr)
df_c <- ldply (counts_all, data.frame)
df1 <- df_c[1:length(rownames(df_c)),2]
#df1
p2 <- hist(df1, main="", 
     , xlab = "Number of UMIs per cell GFP+ a-syn",col = "gray",border = "black", breaks=100)
#######################################
counts_all <- as.data.frame(pbmc_nogfp1$nCount_originalexp)
#library (plyr)
df_c <- ldply (counts_all, data.frame)
df1 <- df_c[1:length(rownames(df_c)),2]
#df1
p3 <- hist(df1, main="", 
     , xlab = "Number of UMIs per cell GFP- 1",col = "gray",border = "black", breaks=100)
#######################################
counts_all <- as.data.frame(pbmc_nogfp2$nCount_originalexp)
#library (plyr)
df_c <- ldply (counts_all, data.frame)
df1 <- df_c[1:length(rownames(df_c)),2]
#df1
p4 <- hist(df1, main="", 
     , xlab = "Number of UMIs per cell GFP- 2",col = "gray",border = "black", breaks=100)

p1 | p2 | p3 | p4
counts_all <- as.data.frame(pbmc_gfp_bfp$nFeature_originalexp)
library (plyr)
df_c <- ldply (counts_all, data.frame)
df1 <- df_c[1:length(rownames(df_c)),2]
#df1
hist(df1, main="", 
     , xlab = "Number of genes per cell GFP+ tagBFP",col = "gray",border = "black", breaks=100)
#######################################
counts_all <- as.data.frame(pbmc_gfp_asyn$nFeature_originalexp)
df_c <- ldply (counts_all, data.frame)
df1 <- df_c[1:length(rownames(df_c)),2]
#df1
hist(df1, main="", 
     , xlab = "Number of genes per cell GFP+ a-syn",col = "gray",border = "black", breaks=100)
#######################################
counts_all <- as.data.frame(pbmc_nogfp1$nFeature_originalexp)
df_c <- ldply (counts_all, data.frame)
df1 <- df_c[1:length(rownames(df_c)),2]
#df1
hist(df1, main="", 
     , xlab = "Number of genes per cell GFP- 1",col = "gray",border = "black", breaks=100)
#######################################
counts_all <- as.data.frame(pbmc_nogfp2$nFeature_originalexp)
df_c <- ldply (counts_all, data.frame)
df1 <- df_c[1:length(rownames(df_c)),2]
#df1
hist(df1, main="", 
     , xlab = "Number of genes per cell GFP- 2",col = "gray",border = "black", breaks=100)

pbmc_gfp_bfp_sub <- subset(pbmc_gfp_bfp, subset = nFeature_originalexp > 0
                           & nFeature_originalexp < 7500 &
                             nCount_originalexp>0 & nCount_originalexp < 60000 )
pbmc_gfp_asyn_sub <- subset(pbmc_gfp_asyn, subset = nFeature_originalexp > 0
                            & nFeature_originalexp < 8000 &
                              nCount_originalexp>0 & nCount_originalexp < 60000)
pbmc_nogfp1_sub <- subset(pbmc_nogfp1, subset = nFeature_originalexp > 0
                          & nFeature_originalexp < 9000 &
                            nCount_originalexp>0 & nCount_originalexp < 10000)
pbmc_nogfp2_sub <- subset(pbmc_nogfp2, subset = nFeature_originalexp > 0
                          & nFeature_originalexp < 8000 &
                            nCount_originalexp>0 & nCount_originalexp < 75000)

r1 = length(colnames(pbmc_nogfp2))
r2 = length(colnames(pbmc_gfp_bfp))
r3 = length(colnames(pbmc_gfp_asyn))
r4 = length(colnames(pbmc_nogfp1))

r1_s = length(colnames(pbmc_nogfp2_sub))
r2_s = length(colnames(pbmc_gfp_bfp_sub))
r3_s = length(colnames(pbmc_gfp_asyn_sub))
r4_s = length(colnames(pbmc_nogfp1_sub))

# df_rows <- c("Rat GFP- 1 (asyn)", "Rat GFP+ (bfp)", "Rat GFP+ (asyn)", "Rat GFP- 2 (asyn)")  #pmbc_c pmbc1 pbmc2 pbmc3
df_rows <- c("Rat GFP+ (bfp)", "Rat GFP+ (asyn)", "Rat GFP- 1 (asyn)", "Rat GFP- 2 (asyn)")  #pmbc_c pmbc1 pbmc2 pbmc3

Before_filt <- c(r2,r3,r1,r4)
After_filt <- c(r2_s,r3_s,r1_s,r4_s)
df <- data.frame(Before_filt, After_filt)
row.names(df) <- df_rows
df
write.csv(df, "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/parse_plots/before_after_filt_stats_cells")

#########################
# Analyse
pbmc_gfp_bfp_sub <- NormalizeData(pbmc_gfp_bfp_sub, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc_gfp_asyn_sub <- NormalizeData(pbmc_gfp_asyn_sub, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc_nogfp1_sub <- NormalizeData(pbmc_nogfp1_sub, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc_nogfp2_sub <- NormalizeData(pbmc_nogfp2_sub, normalization.method = "LogNormalize", scale.factor = 10000)
print("All normalised!")

pbmc_gfp_bfp_sub <- FindVariableFeatures(pbmc_gfp_bfp_sub, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc_gfp_bfp_sub)
pbmc_gfp_bfp_sub <- ScaleData(pbmc_gfp_bfp_sub, features = all.genes)
top10 <- head(VariableFeatures(pbmc_gfp_bfp_sub), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc_gfp_bfp_sub)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = FALSE)
plot1 + plot2

pbmc_gfp_bfp_sub@meta.data$type <- "GFP+_bfp"   #earlier had gfp-_1 and 2 as separate but kept them as the same now
Idents(object = pbmc_gfp_bfp_sub) <- "GFP+_bfp"
#################################
pbmc_gfp_asyn_sub <- FindVariableFeatures(pbmc_gfp_asyn_sub, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc_gfp_asyn_sub)
pbmc_gfp_asyn_sub <- ScaleData(pbmc_gfp_asyn_sub, features = all.genes)
pbmc_gfp_asyn_sub@meta.data$type <- "GFP+_asyn"
Idents(object = pbmc_gfp_asyn_sub) <- "GFP+_asyn"
top10 <- head(VariableFeatures(pbmc_gfp_asyn_sub), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc_gfp_asyn_sub)
plot1
plot2 <- LabelPoints(plot = plot1, points = top10, repel = FALSE)
plot1 + plot2

#################################
pbmc_nogfp1_sub <- FindVariableFeatures(pbmc_nogfp1_sub, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc_nogfp1_sub)
pbmc_nogfp1_sub <- ScaleData(pbmc_nogfp1_sub, features = all.genes)
pbmc_nogfp1_sub@meta.data$type <- "GFP-_asyn1"
Idents(object = pbmc_nogfp1_sub) <- "GFP-_asyn1"
top10 <- head(VariableFeatures(pbmc_nogfp1_sub), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc_nogfp1_sub)
plot1
plot2 <- LabelPoints(plot = plot1, points = top10, repel = FALSE)
plot1 + plot2

#################################

pbmc_nogfp2_sub <- FindVariableFeatures(pbmc_nogfp2_sub, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc_nogfp2_sub)
pbmc_nogfp2_sub <- ScaleData(pbmc_nogfp2_sub, features = all.genes)
pbmc_nogfp2_sub@meta.data$type <- "GFP-_asyn2"
Idents(object = pbmc_nogfp2_sub) <- "GFP-_asyn2"
top10 <- head(VariableFeatures(pbmc_nogfp2_sub), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc_nogfp2_sub)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = FALSE)
plot1 + plot2

print("Var genes found for each sample and scaled!")

pbmc.merged <- merge(x = pbmc_gfp_bfp_sub, y = list(pbmc_nogfp2_sub, pbmc_nogfp1_sub, pbmc_gfp_asyn_sub),
                     add.cell.ids = c("GFP+_bfp", "GFP-_asyn2", "GFP-_asyn1", "GFP+_asyn")
)

# pbmc.merged <- add_aav_meta(pbmc.merged, "AAV-ASYN")

p1 <- DimPlot(pbmc.merged.final)
unique(pbmc.merged.final$AAV_ASYN)
p2 <- FeaturePlot(pbmc.merged, "AAV_ASYN", label = FALSE) + ggtitle("AAV_ASYN copy number")

p1 | p2


# without preprocessing
pbmc.merged <- merge(x = pbmc_gfp_bfp, y = list(pbmc_nogfp2, pbmc_nogfp1, pbmc_gfp_asyn))


# Idents(object = pbmc.merged) <- pbmc.merged@meta.data$AAV.ASYN


FeatureScatter(pbmc.merged, "nCount_RNA", "nFeature_RNA", group.by = "type", pt.size = 0.5)

pbmc.merged <- NormalizeData(pbmc.merged)
pbmc.merged <- FindVariableFeatures(pbmc.merged)
pbmc.merged <- ScaleData(pbmc.merged)
pbmc.merged <- RunPCA(pbmc.merged)
pbmc.merged <- RunUMAP(pbmc.merged, dims=1:30, reduction="pca")
pbmc.merged <- FindNeighbors(pbmc.merged, reduction = "pca", dims = 1:20) #10
pbmc.merged <- FindClusters(pbmc.merged, resolution = 0.5)

DimPlot(pbmc.merged)

table(pbmc.merged$sample)

###############################################################
# Batch effect correction CCA
animals.list <- SplitObject(pbmc.merged.final, split.by = "sample")
animals.list

features <- SelectIntegrationFeatures(object.list = animals.list)
pbmc.anchors <- FindIntegrationAnchors(object.list = animals.list, anchor.features = features)
pbmc.integ <- IntegrateData(anchorset = pbmc.anchors, k.weight = 40)
pbmc.integ <- ScaleData(pbmc.integ, verbose = FALSE)
pbmc.integ <- RunPCA(pbmc.integ, features = VariableFeatures(object = pbmc.integ))
ElbowPlot(pbmc.integ)
pbmc.integ <- RunPCA(pbmc.integ, npcs = 30, verbose = FALSE)
pbmc.integ <- RunUMAP(pbmc.integ, reduction = "pca", dims = 1:7) #10
pbmc.integ <- FindNeighbors(pbmc.integ, reduction = "pca", dims = 1:20) #10
pbmc.integ <- FindClusters(pbmc.integ, resolution = 0.5)

DimPlot(pbmc.integ, reduction = "umap") + ggtitle("Parse batch corrected by CCA")
###############################################################
# Running Harmony batch effect correction
library("harmony")

pbmc.merged.final@assays$originalexp
pbmc.merged.harm <- RunHarmony(pbmc.merged, 'type', assay.use = "originalexp", project.dim = F)
pbmc.merged.harm <- FindNeighbors(pbmc.merged.harm, reduction="harmony", dims = 1:30)
pbmc.merged.harm <- RunUMAP(pbmc.merged.harm, reduction="harmony", dims = 1:30)
pbmc.merged.harm <- FindClusters(pbmc.merged.harm, resolution = 0.5)
DimPlot(pbmc.merged.harm)
###############################################################
rds_out <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/pbmc_integ.rds"
saveRDS(pbmc.integ, rds_out)

rds_out <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/pbmc_harm.rds"
saveRDS(pbmc.merged.harm, rds_out)

p1 <- DimPlot(pbmc.merged) + ggtitle("Parse")
p2 <- DimPlot(pbmc.integ) + ggtitle("CCA")
p3 <- DimPlot(pbmc.merged.harm) + ggtitle("Harmony")
p1 | p2 | p3
table(sce.ref$Celltype_assigned)

################################################################
# Import if not processed on the current script run:
rds_out <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/pbmc_integ.rds"
pbmc.integ <- readRDS(rds_out)

rds_out <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/pbmc_harm.rds"
pbmc.merged.harm <- readRDS(rds_out)

sce.parse <- as.SingleCellExperiment(pbmc.merged)
sce.parse.integ <- as.SingleCellExperiment(pbmc.integ)
sce.parse.harm <- as.SingleCellExperiment(pbmc.merged.harm)
table(pbmc.merged$sample)

sce.ref
# BiocManager::install("SingleR")
library("SingleR")
# Run singleR with the different samples. Save the file as rds (contains only SingleR annotations)

pred <- SingleR(test=sce.parse, ref=sce.ref, labels=sce.ref$Celltype_assigned)
# pred <- SingleR(test=sce.parse.integ, ref=sce.ref, labels=sce.ref$Celltype_assigned)
# pred <- SingleR(test=sce.parse.harm, ref=se, labels=se$label.main)

table(pred$labels)

sce.parse$annotations_1000 <- pred$labels
table(sce.parse$annotations_1000)
pbmc.merged.final <- pbmc.merged
pbmc.merged.final$annotations_1000 <- pred$labels
# does th eglut number of pbmc.merged match to the subset?

rds_out <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/pbmc_ann_preproc.rds"
pbmc.merged <- readRDS(rds_out)

table(pbmc.merged.final$Annotations_specific)

saveRDS(pbmc.merged.final, rds_out)


rds_in <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/pbmc_ann_preproc.rds"

pbmc.merged.final <- readRDS(rds_in)

table(pbmc.merged.final$annotations_1000)


##############################################################
# Visualise some markers and see how they align with the annotations
DotPlot(pbmc.merged.final, group.by = "annotations_1000", features=c('TH', 'SLC6A3', 'DDC', label = FALSE))

DotPlot(pbmc.merged.final, group.by = "annotations_1000", features=c('Gad1', 'Gad2', 'Pax2', 'Slc32a1', label = FALSE))
DotPlot(pbmc.merged.final, group.by = "annotations_1000", features=c('SLC17A7', 'SLC17A6', 'MEIS2','SLC1A1', label = FALSE))
DotPlot(pbmc.merged.final, group.by = "annotations_1000", features=c('Gfap', label = FALSE))
DotPlot(pbmc.merged.final, group.by = "annotations", features=c('SLC17A7', 'SLC17A6', 'MEIS2','SLC1A1', label = FALSE))


p1 <- DimPlot(pbmc.merged.final, group.by = "annotations_1000")

p2 <- FeaturePlot(pbmc.merged.final, reduction = "umap", "AAV_ASYN", label = FALSE) + ggtitle("AAV_ASYN copy number")
p3 <- FeaturePlot(pbmc.merged.final, reduction = "umap", "TH", label = FALSE)
p1
p2 | p3 


#################################################
# Too many glut cells, cant be right, subset as their own and relabel
pbmc.merged.glut <- subset(x = pbmc.merged.final, subset = annotations_1000 == c("Excitatory neurons, midbrain"))
pbmc.merged.glut

pbmc.merged.glut <- NormalizeData(pbmc.merged.glut)
pbmc.merged.glut <- FindVariableFeatures(pbmc.merged.glut)
pbmc.merged.glut <- ScaleData(pbmc.merged.glut)
ElbowPlot(pbmc.merged.glut)
pbmc.merged.glut <- RunPCA(pbmc.merged.glut, npcs = 30, verbose = FALSE)

pbmc.merged.glut <- RunUMAP(pbmc.merged.glut, reduction = "pca", dims = 1:10) #10
pbmc.merged.glut <- FindNeighbors(pbmc.merged.glut, reduction = "pca", dims = 1:20) #10
pbmc.merged.glut <- FindClusters(pbmc.merged.glut, resolution = 1.2)


table(Idents(pbmc.merged.glut))


# only one identity shown even after clustering
DimPlot(pbmc.merged.glut, reduction = "umap")

# Get the markers of the different clusters, save and manually annotate them
markers_glut_data <- FindAllMarkers(pbmc.merged.glut, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, min.diff.pct = 0.3)
head(markers_glut_data)

p <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/Parse_samples_TB/marker_genes_glut_data_subset2.csv"
#write into an output file the cluster x assignment table for later
write.csv(markers_glut_data, p)
DimPlot(pbmc.merged.glut)

# Insert the manual annotations to the pbmc.merged.glut object's clusters
pbmc.merged.glut <- RenameIdents(object = pbmc.merged.glut, 
                            `0` = "Inhibitory neurons, midbrain",
                            `1` = "Excitatory neurons, midbrain",
                            `2` = "Excitatory neurons, midbrain",
                            `3` = "Neurons undefined",
                            `4` = "Interneurons",
                            `5` = "Fibroblasts",
                            `6` = "Oligodendrocyte progenitor cells",
                            `7` = "Neurons undefined",
                            `8` = "Neurons undefined",
                            `9` = "Neurons undefined",
                            `10` = "Neurons undefined",
                            `11` = "Inhibitory neurons, midbrain",
                            `12` = "Inhibitory neurons, midbrain",
                            `13` = "Oligodendrocyte progenitor cells",
                            `14` = "Inhibitory neurons, midbrain",
                            `15` = "Endothelial cells",
                            `16` = "Endothelial cells")


DimPlot(pbmc.merged.glut)
table(pbmc.merged.glut$sample)
table(Idents(pbmc.merged.glut))
pbmc.merged.glut[["annotations"]] <- Idents(object = pbmc.merged.glut)

# table(pbmc.merged$annotations)
pbmc.merged.glut.da <- subset(x = pbmc.merged.glut, subset = annotations == c("Dopaminergic neurons, ventral midbrain (SNc, VTA)"))

table(pbmc.merged.glut.da$sample)

rds_out <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/pbmc_ann_glut_subset_noda.rds"
saveRDS(pbmc.merged.glut, rds_out)

rds_in <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/pbmc_ann_preproc.rds"
pbmc.merged.final <- readRDS(rds_in)
DimPlot(pbmc.merged.final)


# add the glut subset annotations to the final one, i.e. reannotate the glut ones in the full seurat object (pbmc.merged.final)
pbmc.merged.final[["final_annotations"]] <- Idents(object = pbmc.merged.final)


# Subset to DA subtypes which you pass into 2_da_subtype_annotation.py (found inside folder "ref_file_generation_and_custom_annotation") to get DA subtypes and an output of the remade metadata of the DA data. this is then passed (along with full annotation metadata of pbmc merged final) to generate a new annoation file with DA subtypes

# p = "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/annotations_final_nonspecific_da.csv"

write.csv(pbmc.merged.final[["final_annotations"]], p)

seurat.parse.da <- subset(x = pbmc.merged.final, subset = final_annotations == c("Dopaminergic neurons, ventral midbrain (SNc, VTA)"))

seurat.parse.da

table(seurat.parse.da$final_annotations)
p = "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/annotations_final_nonspecific_da_only.csv"


counts_s4 <- seurat.parse.da@assays$originalexp@counts
counts <- as.data.frame(counts_s4)
counts[1:5,1:5]
write.csv(counts, p)

####################################################
full_ann <- as.data.frame(pbmc.merged.final@meta.data$annotations_1000)
rownames(full_ann) <- colnames(pbmc.merged.final)
tail(full_ann)
dim(full_ann)

glut_ann <- as.data.frame(pbmc.merged.glut@meta.data$annotations)
head(pbmc.merged.glut@meta.data)
rownames(glut_ann) <- colnames(pbmc.merged.glut)
tail(glut_ann)
dim(glut_ann)

table(full_ann$`pbmc.merged.final@meta.data$annotations_1000`)

outp <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/"

write.csv(full_ann, paste(outp, "full_ann2.csv", sep=""))
write.csv(glut_ann, paste(outp, "glut_ann2.csv", sep=""))


# final_ann <- read.csv(paste(outp, "final_annotations2.csv", sep=""), row.names="id")
final_ann <- read.csv(paste(outp, "final_annotations2.csv", sep=""))
colnames(final_ann) <- c("cells", "annotations_all_glut")
head(final_ann)

pbmc.merged.final$annotations_all_glut <- final_ann
cells <- final_ann$X
rownames(cells) <- pbmc.merged.final[,1]




final_ann <- "/media/data/AtteR/projects/parsebio/ParsePipeline/docker_singlecell/analysis_stuff/ref_files_final/final_annotations_parse_with_dasubtypes_2.csv"

anns_with_da_subtypes_final <- read.csv(final_ann, row.names="genes")
head(anns_with_da_subtypes_final)
colnames(anns_with_da_subtypes_final) <- "cell_types"
table(anns_with_da_subtypes_final[,1])

table(pbmc.merged.final)

pbmc.merged.final <- AddMetaData(pbmc.merged.final, anns_with_da_subtypes_final, col.name = "Annotations_specific")


Idents(pbmc.merged.final) <- pbmc.merged.final@meta.data$Annotations_specific2
table(pbmc.merged.final$Annotations_specific)

p1 <- DimPlot(pbmc.merged.final)
p2 <-FeaturePlot(pbmc.merged.final, "AAV-ASYN", label = FALSE)
p1 | p2
table(pbmc.merged.final@meta.data$final_annotations)

